/**
 * Builds the Word Lock dictionary artifact from ENABLE1 (public domain).
 * Filters to playable words — 3-12 letters, a-z, no Q since Q is not on the
 * dice — and strips a slur blocklist, then emits the blob the engine installs.
 * Run manually; its output is committed.
 */
import { writeFileSync } from "node:fs";
import {
  MIN_WORD_LENGTH,
  MAX_WORD_LENGTH,
} from "../packages/engine/src/minigames/wordlock/tuning";
import { BLOCKED_WORDS } from "./wordlist-blocklist";

const SOURCE =
  "https://raw.githubusercontent.com/dolph/dictionary/master/enable1.txt";
const OUT = "packages/engine/src/minigames/wordlock/words.generated.ts";

async function main(): Promise<void> {
  const response = await fetch(SOURCE);
  if (!response.ok) throw new Error(`fetch failed: ${response.status}`);
  const blocked = new Set(BLOCKED_WORDS.map((w) => w.toUpperCase()));

  const words = (await response.text())
    .split("\n")
    .map((line) => line.trim().toUpperCase())
    .filter(
      (word) =>
        /^[A-Z]+$/.test(word) &&
        !word.includes("Q") &&
        word.length >= MIN_WORD_LENGTH &&
        word.length <= MAX_WORD_LENGTH &&
        !blocked.has(word),
    )
    .sort();

  const unique = [...new Set(words)];
  writeFileSync(
    OUT,
    `/**\n * Generated by scripts/build-wordlist.ts from ENABLE1 (public domain).\n * Do not edit by hand; rerun \`npm run build:wordlist\` instead.\n */\n\nexport const WORD_BLOB = ${JSON.stringify(unique.join("\n"))};\n`,
  );
  process.stdout.write(`${unique.length} words written to ${OUT}\n`);
}

void main();
